const LARGE_PAYLOAD = [
  {
    _id: '62a2fadc23b5b8490324ac04',
    index: 0,
    guid: '933088c7-e9d8-4a02-a881-1f0a848377b6',
    isActive: true,
    balance: '$1,239.15',
    picture: 'http://placehold.it/32x32',
    age: 36,
    eyeColor: 'brown',
    name: 'Hester Ferguson',
    gender: 'female',
    company: 'QUOTEZART',
    email: 'hesterferguson@quotezart.com',
    phone: '+1 (865) 450-2386',
    address: '518 Lamont Court, Topanga, Texas, 7534',
    about:
      'Irure Lorem magna Lorem aliquip ea qui anim. Magna in pariatur et reprehenderit dolor sint. Sint cupidatat cillum nisi eiusmod Lorem magna laborum cupidatat dolore. Deserunt id commodo do elit ea qui laboris dolor dolor est cupidatat ad velit fugiat. Mollit quis esse consectetur magna enim amet commodo incididunt ex consequat tempor.\r\n',
    registered: '2020-07-16T03:44:31 -02:00',
    latitude: -80.44567,
    longitude: -44.096304,
    tags: [
      'sit',
      'exercitation',
      'minim',
      'fugiat',
      'do',
      'voluptate',
      'culpa',
    ],
    friends: [
      {
        id: 0,
        name: 'Hoover Faulkner',
      },
      {
        id: 1,
        name: 'Bradley Hanson',
      },
      {
        id: 2,
        name: 'Edna Knox',
      },
    ],
    greeting: 'Hello, Hester Ferguson! You have 4 unread messages.',
    favoriteFruit: 'banana',
  },
  {
    _id: '62a2fadc0b1d85a89040646a',
    index: 1,
    guid: '83356bd6-1eba-4ba7-b8de-0cf161ca0281',
    isActive: true,
    balance: '$2,048.65',
    picture: 'http://placehold.it/32x32',
    age: 36,
    eyeColor: 'blue',
    name: 'Delia Salazar',
    gender: 'female',
    company: 'GEEKNET',
    email: 'deliasalazar@geeknet.com',
    phone: '+1 (811) 560-2637',
    address: '699 Canal Avenue, Loretto, Rhode Island, 9709',
    about:
      'Proident ut magna ex do eiusmod ea nostrud veniam laborum quis eiusmod minim cillum labore. Voluptate anim esse consequat exercitation cillum in id nisi laborum esse ea enim. Commodo cillum enim nostrud duis non dolor Lorem labore esse elit ullamco irure labore consequat. Ipsum reprehenderit consequat non sunt qui do adipisicing. Ullamco reprehenderit nostrud esse ex occaecat proident dolore. Lorem ea consectetur elit ea sit consequat tempor. In ullamco ullamco enim sint occaecat sunt amet quis laborum qui ut culpa veniam.\r\n',
    registered: '2016-06-22T10:20:03 -02:00',
    latitude: -18.161649,
    longitude: 77.964289,
    tags: [
      'elit',
      'nisi',
      'cupidatat',
      'pariatur',
      'magna',
      'ullamco',
      'ipsum',
    ],
    friends: [
      {
        id: 0,
        name: 'Kristine Berg',
      },
      {
        id: 1,
        name: 'Stacy Franco',
      },
      {
        id: 2,
        name: 'Angeline Pena',
      },
    ],
    greeting: 'Hello, Delia Salazar! You have 9 unread messages.',
    favoriteFruit: 'strawberry',
  },
  {
    _id: '62a2fadccc374037e017595f',
    index: 2,
    guid: '78553157-f0ed-42a7-b78b-53129ffc0501',
    isActive: false,
    balance: '$2,835.35',
    picture: 'http://placehold.it/32x32',
    age: 35,
    eyeColor: 'brown',
    name: 'Coffey Ellis',
    gender: 'male',
    company: 'EQUITAX',
    email: 'coffeyellis@equitax.com',
    phone: '+1 (822) 420-2422',
    address: '755 Maple Avenue, Esmont, Idaho, 1544',
    about:
      'Ipsum dolore consequat nostrud pariatur quis esse culpa consequat pariatur. Incididunt veniam dolor enim esse labore consectetur dolore sint. Reprehenderit magna nisi deserunt officia et nostrud anim eiusmod non ad. Ex sit deserunt est duis mollit consequat sunt laborum quis nisi et ut. Ex id laboris ea nostrud velit magna est culpa occaecat dolore proident tempor.\r\n',
    registered: '2020-08-08T12:41:04 -02:00',
    latitude: -87.03929,
    longitude: -161.095288,
    tags: ['et', 'officia', 'enim', 'minim', 'aute', 'tempor', 'in'],
    friends: [
      {
        id: 0,
        name: 'Hopkins Mejia',
      },
      {
        id: 1,
        name: 'Rosa Larsen',
      },
      {
        id: 2,
        name: 'Elena Mckenzie',
      },
    ],
    greeting: 'Hello, Coffey Ellis! You have 4 unread messages.',
    favoriteFruit: 'strawberry',
  },
  {
    _id: '62a2fadc42eecfa85c867d9e',
    index: 3,
    guid: '0d69dc13-e1f2-4cd8-9210-edc402915833',
    isActive: true,
    balance: '$2,480.36',
    picture: 'http://placehold.it/32x32',
    age: 24,
    eyeColor: 'brown',
    name: 'Celina Lloyd',
    gender: 'female',
    company: 'ACCUPHARM',
    email: 'celinalloyd@accupharm.com',
    phone: '+1 (972) 464-2126',
    address: '528 Hoyt Street, Kansas, Maryland, 2258',
    about:
      'In labore voluptate minim et ut reprehenderit officia occaecat consequat velit non irure adipisicing. Ex do duis nulla deserunt duis exercitation est minim. Anim veniam commodo amet labore. Deserunt et reprehenderit ex eu laboris eu. Ad amet enim mollit ex. Ad laborum culpa consectetur esse cillum non ut veniam laborum pariatur commodo cupidatat esse.\r\n',
    registered: '2021-07-23T03:05:46 -02:00',
    latitude: -34.795033,
    longitude: -60.592133,
    tags: ['laborum', 'ea', 'esse', 'incididunt', 'anim', 'aliquip', 'id'],
    friends: [
      {
        id: 0,
        name: 'Lenora Osborn',
      },
      {
        id: 1,
        name: 'Graves Mccullough',
      },
      {
        id: 2,
        name: 'Heath Sykes',
      },
    ],
    greeting: 'Hello, Celina Lloyd! You have 9 unread messages.',
    favoriteFruit: 'apple',
  },
  {
    _id: '62a2fadcdbdbc1843f0e1ed0',
    index: 4,
    guid: 'c9c3e73f-e6f2-43e3-a477-cfb1aba588f8',
    isActive: false,
    balance: '$1,213.06',
    picture: 'http://placehold.it/32x32',
    age: 40,
    eyeColor: 'green',
    name: 'Marilyn Ochoa',
    gender: 'female',
    company: 'ECLIPTO',
    email: 'marilynochoa@eclipto.com',
    phone: '+1 (919) 575-3499',
    address: '465 Beard Street, Leyner, Nebraska, 9144',
    about:
      'Duis incididunt proident voluptate laboris commodo do nisi. Fugiat in aute mollit quis fugiat occaecat labore. Reprehenderit occaecat ad qui commodo ex fugiat incididunt laboris ad ut eiusmod ea elit. Labore adipisicing excepteur nisi incididunt veniam ullamco. Voluptate labore in cillum qui magna occaecat minim dolore.\r\n',
    registered: '2020-12-30T02:44:13 -01:00',
    latitude: 22.255899,
    longitude: -72.986103,
    tags: ['irure', 'aute', 'sint', 'voluptate', 'fugiat', 'eu', 'officia'],
    friends: [
      {
        id: 0,
        name: 'Marcia Barton',
      },
      {
        id: 1,
        name: 'Ellis Ramos',
      },
      {
        id: 2,
        name: 'Laura Schneider',
      },
    ],
    greeting: 'Hello, Marilyn Ochoa! You have 7 unread messages.',
    favoriteFruit: 'banana',
  },
  {
    _id: '62a2fadc405ded817422c096',
    index: 5,
    guid: 'adaf882e-6ff8-493f-ad24-94c52ac5e5d7',
    isActive: true,
    balance: '$1,673.65',
    picture: 'http://placehold.it/32x32',
    age: 40,
    eyeColor: 'green',
    name: 'Montoya Shaffer',
    gender: 'male',
    company: 'VALPREAL',
    email: 'montoyashaffer@valpreal.com',
    phone: '+1 (974) 586-3912',
    address: '999 Irvington Place, Deltaville, Kentucky, 5819',
    about:
      'Nulla minim dolore nulla tempor tempor deserunt incididunt exercitation quis Lorem irure quis. Cupidatat ipsum qui sint proident. Elit ex officia reprehenderit minim cillum dolor est sint id velit Lorem.\r\n',
    registered: '2014-09-27T01:55:48 -02:00',
    latitude: -68.714686,
    longitude: -81.781871,
    tags: ['culpa', 'ut', 'incididunt', 'ea', 'nostrud', 'ullamco', 'aliqua'],
    friends: [
      {
        id: 0,
        name: 'Lora Malone',
      },
      {
        id: 1,
        name: 'Carol Lucas',
      },
      {
        id: 2,
        name: 'Hannah Hampton',
      },
    ],
    greeting: 'Hello, Montoya Shaffer! You have 5 unread messages.',
    favoriteFruit: 'apple',
  },
]

module.exports = {
  LARGE_PAYLOAD,
}
